name: Deploy to Contabo

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to VPS via SSH
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: "."
          target: "~/reels-bot"

      - name: SSH and run Docker commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd ~/reels-bot
            docker stop reelsbot || true
            docker rm reelsbot || true
            docker build -t reelsbot .
            docker run -d --name reelsbot --restart=always \
              -e TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} \
              reelsbot
